singleuser:
  image: 
    name: us-central1-docker.pkg.dev/interpreta/dev/test
    tag: latest
  cmd: null

proxy:
  service:
    type: ClusterIP 
  
hub:
  config:
    Authenticator:
      admin_users:
        - shayan
    DummyAuthenticator:
      password: <PLACEHOLDER>
    JupyterHub:
      authenticator_class: dummy